###
POST http://localhost:3000/membership/member/add
content-type: application/json

   [ {
        "firstName": "๋John",
        "lastName": "Doe",
        "dob": "1990-11-11"
    }
   ]

###
PUT http://localhost:3000/membership/member/edit
content-type: application/json

{
    "data":{
        "firstName":"Joe",
        "email":"joe@gmail.com"
    },
    "condition":{
        "firstName":"John"
    }
}

###
DELETE http://localhost:3000/membership/member/delete
content-type: application/json

{
    "condition":{
        "firstName":"Joe"
    }
}

###
GET http://localhost:3000/membership/member/get

###
POST http://localhost:3000/api/membership/member/add
content-type: application/json
application: My Members
module: Membership
objectname: Member
objectmethod: Add
validator: MemberValidator

[
   {
        "firstName": "Apahchon",
        "lastName": "DoeAXRE",
        "gender": 0,
        "registeredDate": "2019-03-09"
    }
]  


